version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-1
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:sqlserver://dtaskserver.database.windows.net:1433;database=db-1;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      SPRING_DATASOURCE_USERNAME: ${SQL_ADMIN_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SQL_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-1
    environment:
      REACT_APP_API_URL: http://backend:8080/api
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
